<a href="https://colab.research.google.com/github/AnhNgoc201/Deeplearning/blob/main/Thuchanh_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

## Tạo mảng 1 chiều

### Cách 1

In [ ]:
import numpy as np
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


### Cách 2

In [ ]:
import numpy as np
a = np.array([1, 9, 15, 39])
print(a)

[ 1  9 15 39]


## Tạo mảng 2 chiều

In [ ]:
import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Tạo mảng 3 chiều

In [ ]:
import numpy as np

d = np.array([[(1., 2., 3.), (4., 5., 6.)],
              [(7., 8., 9.), (10., 11., 12.)]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


## Tạo array giá trị trị ban đầu là 0 hoặc 1


In [ ]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape và Flatten ma trận

### Reshape thay đổi kích thước ma trận


In [ ]:
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
print(e)
print(e.shape)
print(e.reshape(3, 2))
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('Reshape(3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('Reshape(3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('Reshape(2, 3, 2)\n', k)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
Reshape(3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Reshape(3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
Reshape(2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


### Platten là chuyển array nhiều chiều về 1 chiều


In [ ]:
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack


In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
v_stack = np.vstack((f, g))
print('Horizontal Append:\n', h_stack)
print('Vertical Append:\n', v_stack)

Horizontal Append:
 [1. 2. 3. 4. 5. 6.]
Vertical Append:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số ngẫu nhiên

### Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [25 22 55 28  3]
Random 2-D array
 [[98 61 62 12]
 [74 25 21 71]
 [70 25 62 58]]
Random 3-D array
 [[[87 66 36]
  [25 69 31]
  [69  4 65]
  [84 16 53]]

 [[45 88 54]
  [34 83 45]
  [49 44 45]
  [24 17 41]]

 [[55 87 29]
  [82 65 49]
  [ 4 83 57]
  [79 51  4]]]


### Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.19307206 0.14365386 0.01500132 0.41945626 0.68110191]
Random 2-D array
 [[0.23490525 0.29085576 0.90736513 0.59788358]
 [0.09929497 0.53627105 0.64635693 0.85653865]
 [0.30306072 0.93499502 0.97163836 0.44526575]]
Random 3-D array
 [[[0.61555486 0.76838943 0.39979349]
  [0.47295989 0.68869316 0.3372925 ]
  [0.33721234 0.33790567 0.51742869]
  [0.56452752 0.34142707 0.53557763]]

 [[0.6402575  0.74828892 0.28383841]
  [0.11559987 0.83376436 0.73916501]
  [0.91786783 0.3415915  0.36485141]
  [0.30630429 0.02220749 0.43924222]]

 [[0.16445362 0.87244576 0.23419968]
  [0.91418699 0.13943623 0.29540671]
  [0.80658948 0.40637697 0.48770924]
  [0.69777013 0.8885723  0.72087699]]]


### Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5, 0.5, 10)
print(a)

[5.23274284 5.12155157 5.33545508 5.05423638 4.51115979 5.44809057
 4.33665361 5.10919871 3.96198914 4.78324307]


### Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước


In [7]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3,5))
print(b)

[[ 4 16 18 16 18]
 [20 14 12 18 10]
 [ 6  6 10 14 10]]


## Thay đổi giá trị của ma trận

In [8]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Sinh dãy số theo khoảng cho trước

### Dùng hàm arange

In [9]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### Dùng hàm linspace

In [10]:
a = np.linspace(1., 5., num = 10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Index và Slice

### Slice

In [11]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('First row:', a[0])
print('Second row:', a[1])

[[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second row: [4 5 6]


### Index

In [12]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('Second row:', a[:, 1])
print('First row:', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
Second row: [2 5]
First row: [1 4]
First two values of second row: [4 5]


# Thực hành pandas