<a href="https://colab.research.google.com/github/AnhNgoc201/Deeplearning/blob/main/Thuchanh_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

## Tạo mảng 1 chiều

In [2]:
#Tạo array 1 chiều
#Có 2 cách tạo
import numpy as np

#Cách 1
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

#Cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [3]:
#Tạo array 2 chiều
import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
#Tạo array 3 chiều
import numpy as np

d = np.array([[(1., 2., 3.), (4., 5., 6.)],
              [(7., 8., 9.), (10., 11., 12.)]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [5]:
#Tạo array giá trị trị ban đầu là 0 hoặc 1
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Reshape thay đổi kích thước ma trận
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
print(e)
print(e.shape)
print(e.reshape(3, 2))
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('Reshape(3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('Reshape(3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('Reshape(2, 3, 2)\n', k)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
Reshape(3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Reshape(3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
Reshape(2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [7]:
#Platten là chuyển array nhiều chiều về 1 chiều
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [8]:
#Thêm dòng dữ liệu với hstack và vstack
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
v_stack = np.vstack((f, g))
print('Horizontal Append:\n', h_stack)
print('Vertical Append:\n', v_stack)

Horizontal Append:
 [1. 2. 3. 4. 5. 6.]
Vertical Append:
 [[1. 2. 3.]
 [4. 5. 6.]]
