<a href="https://colab.research.google.com/github/AnhNgoc201/Deeplearning/blob/main/Thuchanh_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

## Tạo mảng 1 chiều

### Cách 1

In [ ]:
import numpy as np
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


### Cách 2

In [ ]:
import numpy as np
a = np.array([1, 9, 15, 39])
print(a)

[ 1  9 15 39]


## Tạo mảng 2 chiều

In [ ]:
import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Tạo mảng 3 chiều

In [ ]:
import numpy as np

d = np.array([[(1., 2., 3.), (4., 5., 6.)],
              [(7., 8., 9.), (10., 11., 12.)]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


## Tạo array giá trị trị ban đầu là 0 hoặc 1


In [ ]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape và Flatten ma trận

### Reshape thay đổi kích thước ma trận


In [ ]:
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
print(e)
print(e.shape)
print(e.reshape(3, 2))
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('Reshape(3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('Reshape(3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('Reshape(2, 3, 2)\n', k)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
Reshape(3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Reshape(3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
Reshape(2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


### Platten là chuyển array nhiều chiều về 1 chiều


In [ ]:
import numpy as np

e = np.array([(1, 2, 3), (4, 5, 6)])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1 2 3 4 5 6]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack


In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
v_stack = np.vstack((f, g))
print('Horizontal Append:\n', h_stack)
print('Vertical Append:\n', v_stack)

Horizontal Append:
 [1. 2. 3. 4. 5. 6.]
Vertical Append:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số ngẫu nhiên

### Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [25 22 55 28  3]
Random 2-D array
 [[98 61 62 12]
 [74 25 21 71]
 [70 25 62 58]]
Random 3-D array
 [[[87 66 36]
  [25 69 31]
  [69  4 65]
  [84 16 53]]

 [[45 88 54]
  [34 83 45]
  [49 44 45]
  [24 17 41]]

 [[55 87 29]
  [82 65 49]
  [ 4 83 57]
  [79 51  4]]]


### Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.19307206 0.14365386 0.01500132 0.41945626 0.68110191]
Random 2-D array
 [[0.23490525 0.29085576 0.90736513 0.59788358]
 [0.09929497 0.53627105 0.64635693 0.85653865]
 [0.30306072 0.93499502 0.97163836 0.44526575]]
Random 3-D array
 [[[0.61555486 0.76838943 0.39979349]
  [0.47295989 0.68869316 0.3372925 ]
  [0.33721234 0.33790567 0.51742869]
  [0.56452752 0.34142707 0.53557763]]

 [[0.6402575  0.74828892 0.28383841]
  [0.11559987 0.83376436 0.73916501]
  [0.91786783 0.3415915  0.36485141]
  [0.30630429 0.02220749 0.43924222]]

 [[0.16445362 0.87244576 0.23419968]
  [0.91418699 0.13943623 0.29540671]
  [0.80658948 0.40637697 0.48770924]
  [0.69777013 0.8885723  0.72087699]]]


### Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5, 0.5, 10)
print(a)

[5.23274284 5.12155157 5.33545508 5.05423638 4.51115979 5.44809057
 4.33665361 5.10919871 3.96198914 4.78324307]


### Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước


In [ ]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3,5))
print(b)

[[ 4 16 18 16 18]
 [20 14 12 18 10]
 [ 6  6 10 14 10]]


## Thay đổi giá trị của ma trận

In [ ]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Sinh dãy số theo khoảng cho trước

### Dùng hàm arange

In [ ]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### Dùng hàm linspace

In [ ]:
a = np.linspace(1., 5., num = 10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Index và Slice

### Slice

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('First row:', a[0])
print('Second row:', a[1])

[[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second row: [4 5 6]


### Index

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('Second row:', a[:, 1])
print('First row:', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
Second row: [2 5]
First row: [1 4]
First two values of second row: [4 5]


# Thực hành pandas

## Tìm hiểu đối tượng SERIES

### Tạo pandas series từ list

In [ ]:
import pandas as pd
a = pd.Series([1., 2., 3.])

print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])

print(b)
print('First value:', b['a'])

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0


###Tạo pandas Series từ dictionary

In [ ]:
calories = {
    "day1": 420,
    "day2": 380,
    "day3": 390
}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


## Tạo đối tượng Dataframe

###Chuyển đổi từ mảng dạng Numpy sang Pandas và ngược lại

In [ ]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)

print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)

print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


###Tạo DataFrame mảng 2-chiều có tên cột

In [ ]:
dic = {
    'Name': ['John', 'Smith'],
    'Age': [30, 40]
}

df_dic = pd.DataFrame(dic)

print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [ ]:
# Tạo mảng 20 x 4
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

print(df.head())   # in 5 dòng đầu tiên

        so1       so2       so3       so4
0 -2.074947 -1.595920 -0.414305  0.104851
1  2.069902  1.019260  0.409817 -0.655394
2 -1.493772  2.325795 -0.660522 -0.589839
3  0.678822 -0.000957 -1.049079  1.281098
4 -0.446049 -0.161911  0.777645 -1.076658


###Slice DataFrame

In [ ]:
# Tạo mảng 20 x 4
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

print(df.head())   # in 5 dòng đầu tiên

# Chọn 1 cột
print('Chọn cột so1\n', df['so1'])

# Chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

# Chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

# Chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

# Xóa cột
df = df.drop(columns=['so1', 'so4'])

print(df)

        so1       so2       so3       so4
0 -1.149065 -0.543169  0.736718  1.106268
1  0.646637 -0.295652 -0.731430  0.165761
2  0.251436  0.661820  1.246397 -1.537436
3  0.791288  1.726811 -0.372888 -0.145347
4 -0.033557 -0.889727  0.124048  0.674783
Chọn cột so1
 0    -1.149065
1     0.646637
2     0.251436
3     0.791288
4    -0.033557
5     0.192976
6    -0.362425
7    -0.619455
8     0.887222
9    -0.103927
10   -0.547473
11    1.860500
12   -1.396052
13   -1.125231
14    0.337548
15    0.020526
16    1.784195
17    0.477518
18    0.253324
19    1.433565
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -1.149065 -0.543169  0.736718  1.106268
1  0.646637 -0.295652 -0.731430  0.165761
2  0.251436  0.661820  1.246397 -1.537436
Chọn nhiều cột
          so1       so3
0  -1.149065  0.736718
1   0.646637 -0.731430
2   0.251436  1.246397
3   0.791288 -0.372888
4  -0.033557  0.124048
5   0.192976 -1.325536
6  -0.362425 -1.274343
7  -0.619455 -0.585136


###Nối nhiều DataFrame

In [ ]:
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])

df_concat = pd.concat([df1, df2])

print('Concate to DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n',
      df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values in DataFrame\n',
      df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(
    columns={'Name': 'Surname', 'Age': 'Age_pupil'}
)

print('Rename columns of DataFrame\n', df_rename)

Concate to DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


###Đọc dữ liệu từ CSV

In [ ]:
import pandas as pd

data = {
    'YearsExperience': [1.1, 1.3, 1.5, 2.0, 2.2],
    'Salary': [39343, 46205, 37731, 43525, 39891]
}

df = pd.DataFrame(data)

df.to_csv('Salary_Data.csv', index=False)

print('Đã tạo file Salary_Data.csv')

Đã tạo file Salary_Data.csv


In [ ]:
path = '/content/Salary_Data.csv'

COLUMNS = ['YearsExperience', 'Salary']

df_csv = pd.read_csv(
    path,
    skipinitialspace=True,
    names=COLUMNS,
    index_col=False
)

print(df_csv.head())
print(df_csv.shape)

df_csv1 = pd.read_csv(
    path,
    skipinitialspace=True,
    index_col=False
)

print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience  Salary
0  YearsExperience  Salary
1              1.1   39343
2              1.3   46205
3              1.5   37731
4              2.0   43525
(6, 2)
   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
(5, 2)


###Gom nhóm dữ liệu DataFrame

In [ ]:
# Tạo dữ liệu mẫu
data = {
    'Species': ['Bream', 'Bream', 'Perch', 'Pike', 'Roach'],
    'Weight': [242.0, 290.0, 300.0, 500.0, 120.0],
    'Length1': [23.2, 24.0, 25.0, 30.0, 18.0],
    'Length2': [25.4, 26.3, 27.0, 32.0, 20.0],
    'Length3': [30.0, 31.2, 32.0, 35.0, 22.0],
    'Height': [11.52, 12.48, 10.5, 15.0, 8.0],
    'Width': [4.02, 4.30, 4.5, 5.2, 3.1]
}

df_csv = pd.DataFrame(data)

print(df_csv.head())

# Gom nhóm theo Species và tính trung bình
print(df_csv.groupby(['Species']).mean().head())

# Lấy Weight nhỏ nhất theo Species
print(df_csv.groupby(['Species'])['Weight'].min().head())

# Lấy Weight nhỏ nhất theo Species và Height
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

  Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream   242.0     23.2     25.4     30.0   11.52   4.02
1   Bream   290.0     24.0     26.3     31.2   12.48   4.30
2   Perch   300.0     25.0     27.0     32.0   10.50   4.50
3    Pike   500.0     30.0     32.0     35.0   15.00   5.20
4   Roach   120.0     18.0     20.0     22.0    8.00   3.10
         Weight  Length1  Length2  Length3  Height  Width
Species                                                  
Bream     266.0     23.6    25.85     30.6    12.0   4.16
Perch     300.0     25.0    27.00     32.0    10.5   4.50
Pike      500.0     30.0    32.00     35.0    15.0   5.20
Roach     120.0     18.0    20.00     22.0     8.0   3.10
Species
Bream    242.0
Perch    300.0
Pike     500.0
Roach    120.0
Name: Weight, dtype: float64
Species  Height
Bream    11.52     242.0
         12.48     290.0
Perch    10.50     300.0
Pike     15.00     500.0
Roach    8.00      120.0
Name: Weight, dtype: float64


#Thực hành Tensorflow

In [81]:
import tensorflow as tf

##Biểu diễn một Tensor

###Tensor 0-chiều

In [83]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello world', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello world', shape=(), dtype=string)


###Tensor 1-chiều

In [84]:
# We make this a float tensor
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


###Tensor 2-chiều (ma trận)

In [85]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


###Tensor n-chiều (nhiều trục)

In [87]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


###Thuộc tính của tensor

Một tensor gồm có 3 thuộc tính:
*  Label (name)
*  Dimension (shape)
*  Data type (dtype)

In [89]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])

print(rank_3_tensor)
print('Shape:', rank_3_tensor.shape)
print('Data type:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
Shape: (3, 2, 5)
Data type: <dtype: 'int32'>


###Tạo tensor tự động gán giá trị 0 ban đầu

In [90]:
t_zero = tf.zeros(10)
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [91]:
t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [92]:
t_3_zero = tf.zeros([3, 3, 3])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


###Tạo tensor tự động gán giá trị 1 ban đầu

In [93]:
t_one = tf.ones(10)
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [94]:
t_2_one = tf.ones([3, 3])
print(t_2_one)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [95]:
t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


###Tạo tensor tự động với giá trị bất kỳ

In [96]:
t_1 = tf.fill(3, 10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [97]:
t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


###Tạo tensor 1-chiều với hàm linspace

In [98]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


###Tạo tensor 1-chiều với hàm range

In [99]:
range_tensor = tf.range(3.0, 7, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [100]:
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


###Tạo tensor với giá trị ngẫu nhiên

####Tạo tensor ngẫu nhiên với hàm random.normal

In [101]:
range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([-0.38654006 -0.5056543  -1.0236889  -2.1176288  -1.0506283 ], shape=(5,), dtype=float32)


In [102]:
range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor(
[[ 0.2121306   1.4338789   0.34359223]
 [-0.04886297  2.3225527  -0.57529896]
 [ 0.6462049  -0.7910341   0.08323258]], shape=(3, 3), dtype=float32)


####Tạo tensor ngẫu nhiên với hàm random.truncated_normal

In [103]:
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([-0.20811537  1.6173093  -1.8470773  -0.64866537  0.01869502], shape=(5,), dtype=float32)


In [104]:
range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor(
[[ 0.17680919  0.1333248 ]
 [-0.77987826 -0.8991669 ]
 [ 1.11377     0.2286419 ]], shape=(3, 2), dtype=float32)


In [105]:
range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor(
[[[-0.864915    0.62025034]
  [-0.9836798   1.0059164 ]]

 [[-1.1969446   1.4510038 ]
  [ 1.5774524  -0.38537756]]

 [[-0.97686446  0.19931035]
  [ 0.5400864  -0.8232511 ]]], shape=(3, 2, 2), dtype=float32)


####Tạo tensor ngẫu nhiên với hàm random.uniform

In [106]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([12.522337 19.139818 17.132677 11.864432 17.918045], shape=(5,), dtype=float32)


In [107]:
range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[12.982274 13.086854]
 [16.837482 16.755781]
 [11.495118 12.675114]], shape=(3, 2), dtype=float32)


In [109]:
range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[[14.1968975 10.349193  15.476681  19.445156  10.499896 ]
  [10.504952  19.79696   10.222069  17.249187  17.347961 ]]

 [[11.655268  12.262039  16.863497  14.058047  10.249714 ]
  [17.303944  15.902425  18.076122  15.55661   18.352413 ]]

 [[15.214559  17.229263  19.68994   15.399006  10.461428 ]
  [16.619625  19.267948  11.79306   11.438318  19.014612 ]]], shape=(3, 2, 5), dtype=float32)


####Tạo tensor ngẫu nhiên với hàm random.uniform và dùng shuffle để xáo trộn giá trị trong tensor

In [110]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([19.046492 19.344837 12.107262 12.316333 16.974165], shape=(5,), dtype=float32)
tf.Tensor([12.107262 12.316333 19.344837 16.974165 19.046492], shape=(5,), dtype=float32)


###Chuyển đổi kiểu dữ liệu

In [111]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,'---', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int,'---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


###Các phép toán trong tensorflow

####Tính căn bậc 2 của một tensor scalar

In [112]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


####Cộng 2 tensor

In [113]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


####Nhân 2 tensor

In [114]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [115]:
a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)
